# Source: keto/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-keto
  namespace: default
  labels:
    app.kubernetes.io/name: keto
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keto
      app.kubernetes.io/instance: test-keto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keto
        app.kubernetes.io/instance: test-keto
      annotations:
    spec:
      initContainers:
        -
          name: keto-automigrate
          image: "oryd/keto:v0.6.0-alpha.3"
          imagePullPolicy: IfNotPresent
          command: ["keto"]
          args: ["migrate", "up", "-y", "--all-namespaces", "--config", "/etc/config/keto.yaml"]
          volumeMounts:
            -
              name: keto-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            -
              name: DSN
              valueFrom:
                secretKeyRef:
                  name: keto-secret
                  key: dsn
      volumes:
        -
          name: keto-config-volume
          configMap:
            name: keto-config
      containers:
        - name: keto
          image: "oryd/keto:v0.6.0-alpha.3"
          imagePullPolicy: IfNotPresent
          command: ["keto"]
          args: [
            "serve",
            "all",
            "--config",
            "/etc/config/keto.yaml"
          ]
          volumeMounts:
            -
              name: keto-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            -
              name: DSN
              valueFrom:
                secretKeyRef:
                  name: keto-secret
                  key: dsn
          ports:
            - name: keto-write-api
              containerPort: 4457
              protocol: TCP
            - name: keto-read-api
              containerPort: 4456
              protocol: TCP