# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: keto-api
  namespace: default
  labels:
    app.kubernetes.io/name: keto
spec:
  type: ClusterIP
  ports:
    - port: 4456
      targetPort: keto-api
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: keto